---
title: "**CSCI 1051: Syllabus**"
output:
  html_document:
    css: styles.css
---

**Course Description:**
Deep learning has revolutionized our ability to solve complex problems, but its success often obscures the underlying principles that make it work. This course offers a structured approach to understanding and applying deep learning techniques, beginning with the theoretical foundations of machine learning in linear and logistic regression. We will then generalize these ideas into a three-step deep learning framework (architecture, loss function, and optimizer). Applying this foundation, we will explore modern generative technologies like auto-regressive language models and diffusion. Because the tools we discuss are so powerful, it is important to understand their limitations. To this end, we will also cover techniques for interpreting deep learning predictions and adding safeguards to generated content.

**Prerequisites:** I will assume familiarity with calculus, linear regression, probability, and Python. Beyond coding proficiency, I will assume you are comfortable with derivatives, the chain rule, gradients, matrix multiplication, and probability distributions.

**Structure:** We will meet on Monday, Tuesday, Wednesday, and Thursday at 75 Shannon in Room 202. The lecture is from 10am to 12pm and the discussion is from 2 to 4pm. I will hold my office hours during the last hour of the discussion. If you would like additional time to meet with me, please emial me.

**Resources**: This class is loosely based on Chinmay Hegde's phenomenal graduate Deep Learning [course](https://chinmayhegde.github.io/dl-notes/) at NYU Tandon. For each class, I will post my handwritten slides. I would also like for you to be able to access curated notes. To this end, one of the assignments in the class is to write notes for a topic of your choice.

**Discussion**: Please post all your course related questions on [Canvas](https://middlebury.instructure.com/courses/16004). If your question reveals your solution to a homework problem, please email me instead.

### **Grading**

Your grade in the class will be based on the number of points you earn. You will receive an A if you earn 93 or more points, an A- if you earn between 90 and 92 points (inclusive), a B+ if you earn between 87 and 89 points, etc.

**Participation and Questions (13 points):**
Since winter term classes are smaller, let's take advantage of the opportunity for more engagement. Unless you have a reasonable excuse (e.g. sickness, family emergency), I expect you to attend every lecture and discussion. Whether you are able to attend or not, I expect you to fill out the form linked from the home page to receive credit for engagement (one point per lecture day that you fill it out). Of course, if you are not able to attend in person, you should watch the recorded zoom lecture before filling out the form.

**Problem Sets (52 points):**
There will be one problem per class. In order to encourage engagement with the solutions, your problem set grade will be based both on your solutions and your self-grade of your solutions.

*Part 1: Solutions (3 points per homework problem)* 

It is okay to work on the problems with your classmates. However, you should write your solutions and comment your code by yourself.

*Part 2: Self-grade (1 points per homework problem)*

In order to encourage engagement with the solutions, you will reflect on what you did well in the homework and what you learned. You should submit the self-grade after comparing your answers to the solutions.

**Project (30 points):**
In order to practice implementing the ideas we cover, you will select a topic we cover in class and implement an algorithm we discussed on a data set of your choosing. You will write a report describing your results and what you learned. You will also give a presentation showcasing your code to the class. You can complete your project as an individual or with a partner.

**Curated Notes (5 points):**
Notes are a great resource for augmenting your in-class learning. While I had notes for the prior iteration of this course, I updated the content of this course to account for much of the progress in deep learning in the last two years. Unfortunately, I haven't had time to create a new set of notes to reflect the current content. As such, I would like to ask for your help in writing these notes. I will provide an example for the first class (including the finished product and the source that I'd like to use). Thereafter, students can sign up on [this sheet](https://docs.google.com/spreadsheets/d/18PWX6a_zg5qmj2239nig4vYlq4IUhKRv0tRu2yGz9_A/edit?usp=sharing) to write notes for a topic of your choice. You will have access to my handwritten slides, a zoom recording of the lecture, and any generative model of your choice. Because I hope to use these notes in future iterations of the course (with appropriate acknowledgements, of course), I will grade the notes stringently and allow you to resubmit them once.

**Late Policy:**
I expect all assignments to be turned in on time. If you are unable to turn in an assignment on time, you must email me before the assignment is due to request an extension.

### **Honor Code**
Academic integrity is an important part of your learning experience. You are welcome to use online material and discuss problems with others but you must explicitly acknowledge the outside resources on the work you submit.

If I notice that you have copied someone else's work without proper attribution (such as code from the internet without a reference link or a solution very close to another student's without giving credit), I will give you a warning. After the warning, I will subtract 5 points for every violation.

**Large Language Models:** LLMs (that we learn about in class!) are a powerful tool. However, while they are very good at producing human-like text, they have no inherent sense of 'correctness'. You may use LLMs (as detailed below) but you are wholly responsible for the material you submit.

You may use LLMs for:

- Implementing short blocks of code that you can easily check

- Simple questions whose answers you can easily verify 

Do not use LLMS for:

- Implementing extensive code or code that you don't understand

- Complicated questions (like those on the problem sets) that you would learn from answering yourself

Ultimately, the point of the assignments in this class are for you to practice learning. If you use an LLM in liu of practice, then you deny yourself the chance to learn.

### **Academic Accommodations**
If you have a Letter of Accommodation, it is your responsibility to contact me as early in the term as possible. If you do not have a Letter of Accommodation and you believe you are eligible, please reach out to the ADA Coordinators at ada@middlebury.edu.